//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.FEAfip {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOSolicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class DTOSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.DTOErrorSolicitud[] ErrorSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.DTOEventoSolicitud[] EventoSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecVtoCAEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.DTOObservSolicitud[] ObservacionSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.Ticket TicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nroCompField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puntoVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipoCompField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.DTOErrorSolicitud[] ErrorSolicitud {
            get {
                return this.ErrorSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorSolicitudField, value) != true)) {
                    this.ErrorSolicitudField = value;
                    this.RaisePropertyChanged("ErrorSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.DTOEventoSolicitud[] EventoSolicitud {
            get {
                return this.EventoSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoSolicitudField, value) != true)) {
                    this.EventoSolicitudField = value;
                    this.RaisePropertyChanged("EventoSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecSolicitud {
            get {
                return this.FecSolicitudField;
            }
            set {
                if ((this.FecSolicitudField.Equals(value) != true)) {
                    this.FecSolicitudField = value;
                    this.RaisePropertyChanged("FecSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FecVtoCAE {
            get {
                return this.FecVtoCAEField;
            }
            set {
                if ((object.ReferenceEquals(this.FecVtoCAEField, value) != true)) {
                    this.FecVtoCAEField = value;
                    this.RaisePropertyChanged("FecVtoCAE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.DTOObservSolicitud[] ObservacionSolicitud {
            get {
                return this.ObservacionSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionSolicitudField, value) != true)) {
                    this.ObservacionSolicitudField = value;
                    this.RaisePropertyChanged("ObservacionSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.Ticket Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cae {
            get {
                return this.caeField;
            }
            set {
                if ((object.ReferenceEquals(this.caeField, value) != true)) {
                    this.caeField = value;
                    this.RaisePropertyChanged("cae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idTicket {
            get {
                return this.idTicketField;
            }
            set {
                if ((this.idTicketField.Equals(value) != true)) {
                    this.idTicketField = value;
                    this.RaisePropertyChanged("idTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nroComp {
            get {
                return this.nroCompField;
            }
            set {
                if ((this.nroCompField.Equals(value) != true)) {
                    this.nroCompField = value;
                    this.RaisePropertyChanged("nroComp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puntoVenta {
            get {
                return this.puntoVentaField;
            }
            set {
                if ((this.puntoVentaField.Equals(value) != true)) {
                    this.puntoVentaField = value;
                    this.RaisePropertyChanged("puntoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.respuestaField, value) != true)) {
                    this.respuestaField = value;
                    this.RaisePropertyChanged("respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipoComp {
            get {
                return this.tipoCompField;
            }
            set {
                if ((this.tipoCompField.Equals(value) != true)) {
                    this.tipoCompField = value;
                    this.RaisePropertyChanged("tipoComp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class Ticket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.Solicitud[] SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long cuitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime expirationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime generationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.Solicitud[] Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long cuit {
            get {
                return this.cuitField;
            }
            set {
                if ((this.cuitField.Equals(value) != true)) {
                    this.cuitField = value;
                    this.RaisePropertyChanged("cuit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expirationTime {
            get {
                return this.expirationTimeField;
            }
            set {
                if ((this.expirationTimeField.Equals(value) != true)) {
                    this.expirationTimeField = value;
                    this.RaisePropertyChanged("expirationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime generationTime {
            get {
                return this.generationTimeField;
            }
            set {
                if ((this.generationTimeField.Equals(value) != true)) {
                    this.generationTimeField = value;
                    this.RaisePropertyChanged("generationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service {
            get {
                return this.serviceField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceField, value) != true)) {
                    this.serviceField = value;
                    this.RaisePropertyChanged("service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sign {
            get {
                return this.signField;
            }
            set {
                if ((object.ReferenceEquals(this.signField, value) != true)) {
                    this.signField = value;
                    this.RaisePropertyChanged("sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenField, value) != true)) {
                    this.tokenField = value;
                    this.RaisePropertyChanged("token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOErrorSolicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class DTOErrorSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodError {
            get {
                return this.CodErrorField;
            }
            set {
                if ((this.CodErrorField.Equals(value) != true)) {
                    this.CodErrorField = value;
                    this.RaisePropertyChanged("CodError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescError {
            get {
                return this.DescErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DescErrorField, value) != true)) {
                    this.DescErrorField = value;
                    this.RaisePropertyChanged("DescError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOEventoSolicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class DTOEventoSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescEventField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodEvent {
            get {
                return this.CodEventField;
            }
            set {
                if ((this.CodEventField.Equals(value) != true)) {
                    this.CodEventField = value;
                    this.RaisePropertyChanged("CodEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEvent {
            get {
                return this.DescEventField;
            }
            set {
                if ((object.ReferenceEquals(this.DescEventField, value) != true)) {
                    this.DescEventField = value;
                    this.RaisePropertyChanged("DescEvent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOObservSolicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class DTOObservSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodObservField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescObservField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodObserv {
            get {
                return this.CodObservField;
            }
            set {
                if ((this.CodObservField.Equals(value) != true)) {
                    this.CodObservField = value;
                    this.RaisePropertyChanged("CodObserv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescObserv {
            get {
                return this.DescObservField;
            }
            set {
                if ((object.ReferenceEquals(this.DescObservField, value) != true)) {
                    this.DescObservField = value;
                    this.RaisePropertyChanged("DescObserv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.ErrorSolicitud[] ErrorSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.EventoSolicitud[] EventoSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FecSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecVtoCAEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.ObservacionSolicitud[] ObservacionSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.Ticket TicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long nroCompField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int puntoVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipoCompField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.ErrorSolicitud[] ErrorSolicitud {
            get {
                return this.ErrorSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorSolicitudField, value) != true)) {
                    this.ErrorSolicitudField = value;
                    this.RaisePropertyChanged("ErrorSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.EventoSolicitud[] EventoSolicitud {
            get {
                return this.EventoSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoSolicitudField, value) != true)) {
                    this.EventoSolicitudField = value;
                    this.RaisePropertyChanged("EventoSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecSolicitud {
            get {
                return this.FecSolicitudField;
            }
            set {
                if ((this.FecSolicitudField.Equals(value) != true)) {
                    this.FecSolicitudField = value;
                    this.RaisePropertyChanged("FecSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FecVtoCAE {
            get {
                return this.FecVtoCAEField;
            }
            set {
                if ((object.ReferenceEquals(this.FecVtoCAEField, value) != true)) {
                    this.FecVtoCAEField = value;
                    this.RaisePropertyChanged("FecVtoCAE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.ObservacionSolicitud[] ObservacionSolicitud {
            get {
                return this.ObservacionSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionSolicitudField, value) != true)) {
                    this.ObservacionSolicitudField = value;
                    this.RaisePropertyChanged("ObservacionSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.Ticket Ticket {
            get {
                return this.TicketField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketField, value) != true)) {
                    this.TicketField = value;
                    this.RaisePropertyChanged("Ticket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cae {
            get {
                return this.caeField;
            }
            set {
                if ((object.ReferenceEquals(this.caeField, value) != true)) {
                    this.caeField = value;
                    this.RaisePropertyChanged("cae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idTicket {
            get {
                return this.idTicketField;
            }
            set {
                if ((this.idTicketField.Equals(value) != true)) {
                    this.idTicketField = value;
                    this.RaisePropertyChanged("idTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long nroComp {
            get {
                return this.nroCompField;
            }
            set {
                if ((this.nroCompField.Equals(value) != true)) {
                    this.nroCompField = value;
                    this.RaisePropertyChanged("nroComp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puntoVenta {
            get {
                return this.puntoVentaField;
            }
            set {
                if ((this.puntoVentaField.Equals(value) != true)) {
                    this.puntoVentaField = value;
                    this.RaisePropertyChanged("puntoVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respuesta {
            get {
                return this.respuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.respuestaField, value) != true)) {
                    this.respuestaField = value;
                    this.RaisePropertyChanged("respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipoComp {
            get {
                return this.tipoCompField;
            }
            set {
                if ((this.tipoCompField.Equals(value) != true)) {
                    this.tipoCompField = value;
                    this.RaisePropertyChanged("tipoComp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSolicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class ErrorSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.Solicitud SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idSolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodError {
            get {
                return this.CodErrorField;
            }
            set {
                if ((this.CodErrorField.Equals(value) != true)) {
                    this.CodErrorField = value;
                    this.RaisePropertyChanged("CodError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescError {
            get {
                return this.DescErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DescErrorField, value) != true)) {
                    this.DescErrorField = value;
                    this.RaisePropertyChanged("DescError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.Solicitud Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idSolicitud {
            get {
                return this.idSolicitudField;
            }
            set {
                if ((this.idSolicitudField.Equals(value) != true)) {
                    this.idSolicitudField = value;
                    this.RaisePropertyChanged("idSolicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoSolicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class EventoSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.Solicitud SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idSolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodEvent {
            get {
                return this.CodEventField;
            }
            set {
                if ((this.CodEventField.Equals(value) != true)) {
                    this.CodEventField = value;
                    this.RaisePropertyChanged("CodEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEvent {
            get {
                return this.DescEventField;
            }
            set {
                if ((object.ReferenceEquals(this.DescEventField, value) != true)) {
                    this.DescEventField = value;
                    this.RaisePropertyChanged("DescEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.Solicitud Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idSolicitud {
            get {
                return this.idSolicitudField;
            }
            set {
                if ((this.idSolicitudField.Equals(value) != true)) {
                    this.idSolicitudField = value;
                    this.RaisePropertyChanged("idSolicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObservacionSolicitud", Namespace="http://schemas.datacontract.org/2004/07/WcfFactElect")]
    [System.SerializableAttribute()]
    public partial class ObservacionSolicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodObservField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescObservField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Desktop.FEAfip.Solicitud SolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idSolicitudField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodObserv {
            get {
                return this.CodObservField;
            }
            set {
                if ((this.CodObservField.Equals(value) != true)) {
                    this.CodObservField = value;
                    this.RaisePropertyChanged("CodObserv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescObserv {
            get {
                return this.DescObservField;
            }
            set {
                if ((object.ReferenceEquals(this.DescObservField, value) != true)) {
                    this.DescObservField = value;
                    this.RaisePropertyChanged("DescObserv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Desktop.FEAfip.Solicitud Solicitud {
            get {
                return this.SolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitudField, value) != true)) {
                    this.SolicitudField = value;
                    this.RaisePropertyChanged("Solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idSolicitud {
            get {
                return this.idSolicitudField;
            }
            set {
                if ((this.idSolicitudField.Equals(value) != true)) {
                    this.idSolicitudField = value;
                    this.RaisePropertyChanged("idSolicitud");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FEAfip.IServicioCAE")]
    public interface IServicioCAE {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/solicitar", ReplyAction="http://tempuri.org/IServicioCAE/solicitarResponse")]
        Desktop.FEAfip.DTOSolicitud solicitar(int tipoComp, int pv, int concepto, int tdoc, long ndoc, long comp, string fecha, double total, double neto, double iva, string mon, double cotiz, double[][] arrayIva, long[][] compAsociados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/solicitar", ReplyAction="http://tempuri.org/IServicioCAE/solicitarResponse")]
        System.Threading.Tasks.Task<Desktop.FEAfip.DTOSolicitud> solicitarAsync(int tipoComp, int pv, int concepto, int tdoc, long ndoc, long comp, string fecha, double total, double neto, double iva, string mon, double cotiz, double[][] arrayIva, long[][] compAsociados);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/obtenerUltimaSolicitudConError", ReplyAction="http://tempuri.org/IServicioCAE/obtenerUltimaSolicitudConErrorResponse")]
        Desktop.FEAfip.DTOSolicitud obtenerUltimaSolicitudConError(int tipoComp, int ptoVta, long nroComp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/obtenerUltimaSolicitudConError", ReplyAction="http://tempuri.org/IServicioCAE/obtenerUltimaSolicitudConErrorResponse")]
        System.Threading.Tasks.Task<Desktop.FEAfip.DTOSolicitud> obtenerUltimaSolicitudConErrorAsync(int tipoComp, int ptoVta, long nroComp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/ObtenerUltimoAut", ReplyAction="http://tempuri.org/IServicioCAE/ObtenerUltimoAutResponse")]
        int ObtenerUltimoAut(int tipoComp, int ptoVta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/ObtenerUltimoAut", ReplyAction="http://tempuri.org/IServicioCAE/ObtenerUltimoAutResponse")]
        System.Threading.Tasks.Task<int> ObtenerUltimoAutAsync(int tipoComp, int ptoVta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/ConsultarCAE", ReplyAction="http://tempuri.org/IServicioCAE/ConsultarCAEResponse")]
        Desktop.FEAfip.DTOSolicitud ConsultarCAE(int tipoComp, int ptoVta, long nroComp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/ConsultarCAE", ReplyAction="http://tempuri.org/IServicioCAE/ConsultarCAEResponse")]
        System.Threading.Tasks.Task<Desktop.FEAfip.DTOSolicitud> ConsultarCAEAsync(int tipoComp, int ptoVta, long nroComp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/EstadoServidores", ReplyAction="http://tempuri.org/IServicioCAE/EstadoServidoresResponse")]
        string[] EstadoServidores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/EstadoServidores", ReplyAction="http://tempuri.org/IServicioCAE/EstadoServidoresResponse")]
        System.Threading.Tasks.Task<string[]> EstadoServidoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/ObtenerMonHabilitadas", ReplyAction="http://tempuri.org/IServicioCAE/ObtenerMonHabilitadasResponse")]
        string[][] ObtenerMonHabilitadas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCAE/ObtenerMonHabilitadas", ReplyAction="http://tempuri.org/IServicioCAE/ObtenerMonHabilitadasResponse")]
        System.Threading.Tasks.Task<string[][]> ObtenerMonHabilitadasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCAEChannel : Desktop.FEAfip.IServicioCAE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCAEClient : System.ServiceModel.ClientBase<Desktop.FEAfip.IServicioCAE>, Desktop.FEAfip.IServicioCAE {
        
        public ServicioCAEClient() {
        }
        
        public ServicioCAEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCAEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCAEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCAEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Desktop.FEAfip.DTOSolicitud solicitar(int tipoComp, int pv, int concepto, int tdoc, long ndoc, long comp, string fecha, double total, double neto, double iva, string mon, double cotiz, double[][] arrayIva, long[][] compAsociados) {
            return base.Channel.solicitar(tipoComp, pv, concepto, tdoc, ndoc, comp, fecha, total, neto, iva, mon, cotiz, arrayIva, compAsociados);
        }
        
        public System.Threading.Tasks.Task<Desktop.FEAfip.DTOSolicitud> solicitarAsync(int tipoComp, int pv, int concepto, int tdoc, long ndoc, long comp, string fecha, double total, double neto, double iva, string mon, double cotiz, double[][] arrayIva, long[][] compAsociados) {
            return base.Channel.solicitarAsync(tipoComp, pv, concepto, tdoc, ndoc, comp, fecha, total, neto, iva, mon, cotiz, arrayIva, compAsociados);
        }
        
        public Desktop.FEAfip.DTOSolicitud obtenerUltimaSolicitudConError(int tipoComp, int ptoVta, long nroComp) {
            return base.Channel.obtenerUltimaSolicitudConError(tipoComp, ptoVta, nroComp);
        }
        
        public System.Threading.Tasks.Task<Desktop.FEAfip.DTOSolicitud> obtenerUltimaSolicitudConErrorAsync(int tipoComp, int ptoVta, long nroComp) {
            return base.Channel.obtenerUltimaSolicitudConErrorAsync(tipoComp, ptoVta, nroComp);
        }
        
        public int ObtenerUltimoAut(int tipoComp, int ptoVta) {
            return base.Channel.ObtenerUltimoAut(tipoComp, ptoVta);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerUltimoAutAsync(int tipoComp, int ptoVta) {
            return base.Channel.ObtenerUltimoAutAsync(tipoComp, ptoVta);
        }
        
        public Desktop.FEAfip.DTOSolicitud ConsultarCAE(int tipoComp, int ptoVta, long nroComp) {
            return base.Channel.ConsultarCAE(tipoComp, ptoVta, nroComp);
        }
        
        public System.Threading.Tasks.Task<Desktop.FEAfip.DTOSolicitud> ConsultarCAEAsync(int tipoComp, int ptoVta, long nroComp) {
            return base.Channel.ConsultarCAEAsync(tipoComp, ptoVta, nroComp);
        }
        
        public string[] EstadoServidores() {
            return base.Channel.EstadoServidores();
        }
        
        public System.Threading.Tasks.Task<string[]> EstadoServidoresAsync() {
            return base.Channel.EstadoServidoresAsync();
        }
        
        public string[][] ObtenerMonHabilitadas() {
            return base.Channel.ObtenerMonHabilitadas();
        }
        
        public System.Threading.Tasks.Task<string[][]> ObtenerMonHabilitadasAsync() {
            return base.Channel.ObtenerMonHabilitadasAsync();
        }
    }
}
