//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloPlanta
    {
        public ArticuloPlanta()
        {
            this.ArticuloPlantaHistorico = new HashSet<ArticuloPlantaHistorico>();
            this.PreciosAdicionales = new HashSet<PreciosAdicionales>();
        }
    
        public long idArticulo { get; set; }
        public long idPlanta { get; set; }
        public int contador { get; set; }
        public int idMoneda { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fechaCambio { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Planta Planta { get; set; }
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual ICollection<ArticuloPlantaHistorico> ArticuloPlantaHistorico { get; set; }
        public virtual ICollection<PreciosAdicionales> PreciosAdicionales { get; set; }
    }
}
