//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloPlantaHistorico
    {
        public long id { get; set; }
        public long idArticulo { get; set; }
        public long idPlanta { get; set; }
        public int idMoneda { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fechaCambio { get; set; }
    
        public virtual ArticuloPlanta ArticuloPlanta { get; set; }
    }
}
