//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloPlanta
    {
        public ArticuloPlanta()
        {
            this.ArticuloPlantaHistorico = new HashSet<ArticuloPlantaHistorico>();
            this.PreciosAdicionales = new HashSet<PreciosAdicionales>();
        }
    
        public long idArticulo { get; set; }
        public long idPlanta { get; set; }
        public int contador { get; set; }
        public int idMoneda { get; set; }
        public decimal precio { get; set; }
        public System.DateTime fechaCambio { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Planta Planta { get; set; }
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual ICollection<ArticuloPlantaHistorico> ArticuloPlantaHistorico { get; set; }
        public virtual ICollection<PreciosAdicionales> PreciosAdicionales { get; set; }
    }
}
