//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public Banco()
        {
            this.Pago_Cheque = new HashSet<Pago_Cheque>();
        }
    
        public short Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Pago_Cheque> Pago_Cheque { get; set; }
    }
}
