//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraRutinaFirmantes
    {
        public CabeceraRutinaFirmantes()
        {
            this.CabeceraRutina = new HashSet<CabeceraRutina>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public byte[] firma { get; set; }
        public string iniciales { get; set; }
    
        public virtual ICollection<CabeceraRutina> CabeceraRutina { get; set; }
    }
}
