//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraRutinaFirmantes
    {
        public CabeceraRutinaFirmantes()
        {
            this.CabeceraRutina = new HashSet<CabeceraRutina>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public byte[] firma { get; set; }
        public string iniciales { get; set; }
    
        public virtual ICollection<CabeceraRutina> CabeceraRutina { get; set; }
    }
}
