//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraRutina
    {
        public CabeceraRutina()
        {
            this.DatosRutina = new HashSet<DatosRutina>();
        }
    
        public long id { get; set; }
        public Nullable<long> idPlanta { get; set; }
        public Nullable<System.DateTime> fechaMuestreo { get; set; }
        public Nullable<System.DateTime> fechaAnalisis { get; set; }
        public string observaciones { get; set; }
        public string tipoRutina { get; set; }
        public int idCabeceraRutinaFirmante { get; set; }
        public Nullable<int> numeroInterno { get; set; }
        public Nullable<System.DateTime> fechaCargaSistema { get; set; }
    
        public virtual Planta Planta { get; set; }
        public virtual ICollection<DatosRutina> DatosRutina { get; set; }
        public virtual CabeceraRutinaFirmantes CabeceraRutinaFirmantes { get; set; }
    }
}
