//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Planta = new HashSet<Planta>();
            this.Salida = new HashSet<Salida>();
        }
    
        public long id { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public string razonSocial { get; set; }
        public string nombreContacto { get; set; }
        public string cargoContacto { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string telefono2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string cuit { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string motivoBaja { get; set; }
        public Nullable<long> idLocalidad { get; set; }
        public Nullable<int> idSituacionFrenteIva { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual SituacionFrenteIva SituacionFrenteIva { get; set; }
        public virtual ICollection<Planta> Planta { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
        public virtual Saldos Saldos { get; set; }
    }
}
