//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Recibo : Comprobante
    {
        public Comprobante_Recibo()
        {
            this.ItemRecibo = new HashSet<ItemRecibo>();
            this.InstrumentoPago = new HashSet<InstrumentoPago>();
        }
    
        public string formaPago { get; set; }
        public long numero { get; set; }
        public Nullable<byte> IdTipoPago { get; set; }
    
        public virtual ICollection<ItemRecibo> ItemRecibo { get; set; }
        public virtual TipoPagoCliente TipoPagoCliente { get; set; }
        public virtual ICollection<InstrumentoPago> InstrumentoPago { get; set; }
    }
}
