//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public Comprobante()
        {
            this.Comprobante_DevolucionAnul = new HashSet<Comprobante_Devolucion>();
            this.Comprobante_RecargoAnul = new HashSet<Comprobante_Recargo>();
            this.VentaArticuloPlanta = new HashSet<VentaArticuloPlanta>();
        }
    
        public long id { get; set; }
        public decimal importe { get; set; }
        public System.DateTime fechaIngreso { get; set; }
        public bool debe { get; set; }
        public long idPlanta { get; set; }
        public decimal subtotal { get; set; }
        public decimal totalIva { get; set; }
        public Nullable<bool> anulado { get; set; }
        public int estadoCarga { get; set; }
    
        public virtual Planta Planta { get; set; }
        public virtual EstadoComprobante EstadoComprobante { get; set; }
        public virtual ICollection<Comprobante_Devolucion> Comprobante_DevolucionAnul { get; set; }
        public virtual ICollection<Comprobante_Recargo> Comprobante_RecargoAnul { get; set; }
        public virtual ICollection<VentaArticuloPlanta> VentaArticuloPlanta { get; set; }
    }
}
