//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Factura : Comprobante
    {
        public Comprobante_Factura()
        {
            this.Comprobante_Remito = new HashSet<Comprobante_Remito>();
        }
    
        public string observacion { get; set; }
        public long numero { get; set; }
        public System.DateTime vencimiento { get; set; }
        public string condVta { get; set; }
        public string tipo { get; set; }
        public string ordenCompra { get; set; }
        public Nullable<int> idMoneda { get; set; }
        public string cae { get; set; }
        public Nullable<System.DateTime> fecVtoCae { get; set; }
        public int pv { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual ICollection<Comprobante_Remito> Comprobante_Remito { get; set; }
    }
}
