//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Recargo : Comprobante
    {
        public Comprobante_Recargo()
        {
            this.ItemNota = new HashSet<ItemNota>();
        }
    
        public string motivo { get; set; }
        public long numero { get; set; }
        public string condVta { get; set; }
        public string tipo { get; set; }
        public int pv { get; set; }
        public Nullable<long> idComprobante { get; set; }
        public string cae { get; set; }
        public Nullable<System.DateTime> fecVtoCae { get; set; }
        public int idMoneda { get; set; }
    
        public virtual Comprobante ComprobanteAnul { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual ICollection<ItemNota> ItemNota { get; set; }
    }
}
