//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Remito : Comprobante
    {
        public Comprobante_Remito()
        {
            this.Comprobante_Factura = new HashSet<Comprobante_Factura>();
            this.VentaArticuloPlanta1 = new HashSet<VentaArticuloPlanta>();
        }
    
        public string observacion { get; set; }
        public Nullable<int> cantidadBultos { get; set; }
        public long numero { get; set; }
        public decimal pesoTotalKg { get; set; }
        public string ordenCompra { get; set; }
        public Nullable<int> idUnidad { get; set; }
        public string tipo { get; set; }
        public int idMoneda { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Unidad Unidad { get; set; }
        public virtual ICollection<Comprobante_Factura> Comprobante_Factura { get; set; }
        public virtual ICollection<VentaArticuloPlanta> VentaArticuloPlanta1 { get; set; }
    }
}
