//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante_Remito : Comprobante
    {
        public Comprobante_Remito()
        {
            this.Comprobante_Factura = new HashSet<Comprobante_Factura>();
            this.VentaArticuloPlanta1 = new HashSet<VentaArticuloPlanta>();
        }
    
        public string observacion { get; set; }
        public Nullable<int> cantidadBultos { get; set; }
        public long numero { get; set; }
        public decimal pesoTotalKg { get; set; }
        public string ordenCompra { get; set; }
        public Nullable<int> idUnidad { get; set; }
        public string tipo { get; set; }
        public int idMoneda { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Unidad Unidad { get; set; }
        public virtual ICollection<Comprobante_Factura> Comprobante_Factura { get; set; }
        public virtual ICollection<VentaArticuloPlanta> VentaArticuloPlanta1 { get; set; }
    }
}
