//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComposicionArticulos
    {
        public long id { get; set; }
        public long idArticuloPadre { get; set; }
        public long idArticuloHijo { get; set; }
        public decimal cantComposicion { get; set; }
        public decimal factorConversion { get; set; }
    
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual TipoArticulo TipoArticulo1 { get; set; }
    }
}
