//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosRutina
    {
        public long id { get; set; }
        public long idMuestra { get; set; }
        public long idDeterminante { get; set; }
        public long idCabeceraRutina { get; set; }
        public string valor { get; set; }
    
        public virtual CabeceraRutina CabeceraRutina { get; set; }
        public virtual Determinante Determinante { get; set; }
        public virtual Muestra Muestra { get; set; }
    }
}
