//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosRutina
    {
        public long id { get; set; }
        public long idMuestra { get; set; }
        public long idDeterminante { get; set; }
        public long idCabeceraRutina { get; set; }
        public string valor { get; set; }
    
        public virtual CabeceraRutina CabeceraRutina { get; set; }
        public virtual Determinante Determinante { get; set; }
        public virtual Muestra Muestra { get; set; }
    }
}
