//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Determinante
    {
        public Determinante()
        {
            this.DatosRutina = new HashSet<DatosRutina>();
            this.DeterminantesPlanta = new HashSet<DeterminantesPlanta>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public string unidad { get; set; }
        public Nullable<short> grupo { get; set; }
    
        public virtual ICollection<DatosRutina> DatosRutina { get; set; }
        public virtual ICollection<DeterminantesPlanta> DeterminantesPlanta { get; set; }
    }
}
