//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada
    {
        public long id { get; set; }
        public int idPresentacion { get; set; }
        public string nroLote { get; set; }
        public decimal cantidad { get; set; }
        public string concepto { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual Lote Lote { get; set; }
        public virtual Presentacion Presentacion { get; set; }
    }
}
