//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularioUsuario
    {
        public long idFormulario { get; set; }
        public int idUsuario { get; set; }
        public int id { get; set; }
    
        public virtual Formulario Formulario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
