//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        public Formulario()
        {
            this.FormularioUsuario = new HashSet<FormularioUsuario>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<FormularioUsuario> FormularioUsuario { get; set; }
    }
}
