//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRecibo
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> fechaIzq { get; set; }
        public string descripIzq { get; set; }
        public Nullable<decimal> importeIzq { get; set; }
        public Nullable<System.DateTime> fechaDer { get; set; }
        public string descripDer { get; set; }
        public Nullable<decimal> importeDer { get; set; }
        public long idRecibo { get; set; }
    
        public virtual Comprobante_Recibo Comprobante_Recibo { get; set; }
    }
}
