//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemNota
    {
        public long Id { get; set; }
        public string descripcion { get; set; }
        public decimal importe { get; set; }
        public Nullable<long> idRecargo { get; set; }
        public Nullable<long> idDevolucion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> iva { get; set; }
    
        public virtual Comprobante_Devolucion Comprobante_Comprobante_Devolucion { get; set; }
        public virtual Comprobante_Recargo Comprobante_Comprobante_Recargo { get; set; }
    }
}
