//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRecibo
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> fechaIzq { get; set; }
        public string descripIzq { get; set; }
        public Nullable<decimal> importeIzq { get; set; }
        public Nullable<System.DateTime> fechaDer { get; set; }
        public string descripDer { get; set; }
        public Nullable<decimal> importeDer { get; set; }
        public long idRecibo { get; set; }
    
        public virtual Comprobante_Recibo Comprobante_Recibo { get; set; }
    }
}
