//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemNota
    {
        public long Id { get; set; }
        public string descripcion { get; set; }
        public decimal importe { get; set; }
        public Nullable<long> idRecargo { get; set; }
        public Nullable<long> idDevolucion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> iva { get; set; }
    
        public virtual Comprobante_Devolucion Comprobante_Comprobante_Devolucion { get; set; }
        public virtual Comprobante_Recargo Comprobante_Comprobante_Recargo { get; set; }
    }
}
