//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public Localidad()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Planta1 = new HashSet<Planta>();
            this.Proveedor = new HashSet<Proveedor>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public bool inactiva { get; set; }
        public Nullable<int> codigoPostal { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Planta> Planta1 { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}
