//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidad
    {
        public Localidad()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Planta1 = new HashSet<Planta>();
        }
    
        public long id { get; set; }
        public string nombre { get; set; }
        public bool inactiva { get; set; }
        public Nullable<int> codigoPostal { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Planta> Planta1 { get; set; }
    }
}
