//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long id { get; set; }
        public string operacion { get; set; }
        public string detalle { get; set; }
        public string nombreEntidad { get; set; }
        public Nullable<long> idEntidad { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechahora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
