//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long id { get; set; }
        public string operacion { get; set; }
        public string detalle { get; set; }
        public string nombreEntidad { get; set; }
        public Nullable<long> idEntidad { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechahora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
