//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public Lote()
        {
            this.Entrada = new HashSet<Entrada>();
            this.Salida = new HashSet<Salida>();
        }
    
        public string numero { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public long idTipoArticulo { get; set; }
        public Nullable<System.DateTime> fechaElaboracion { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
    
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
    }
}
