//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lote
    {
        public Lote()
        {
            this.Entrada = new HashSet<Entrada>();
            this.Salida = new HashSet<Salida>();
        }
    
        public string numero { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public long idTipoArticulo { get; set; }
        public Nullable<System.DateTime> fechaElaboracion { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
    
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
    }
}
