//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailFactura
    {
        public long Id { get; set; }
        public long IdFactura { get; set; }
        public string Destinatario { get; set; }
        public string Copia { get; set; }
    
        public virtual Comprobante_Factura Comprobante_Comprobante_Factura { get; set; }
    }
}
