//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public Moneda()
        {
            this.Comprobante_Comprobante_Factura = new HashSet<Comprobante_Factura>();
            this.Comprobante_Comprobante_Devolucion = new HashSet<Comprobante_Devolucion>();
            this.Comprobante_Comprobante_Recargo = new HashSet<Comprobante_Recargo>();
            this.Comprobante_Comprobante_Remito = new HashSet<Comprobante_Remito>();
            this.VentaArticuloPlanta = new HashSet<VentaArticuloPlanta>();
            this.ArticuloPlanta = new HashSet<ArticuloPlanta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string simbologia { get; set; }
        public decimal cotizacion { get; set; }
        public string abrevAfip { get; set; }
    
        public virtual ICollection<Comprobante_Factura> Comprobante_Comprobante_Factura { get; set; }
        public virtual ICollection<Comprobante_Devolucion> Comprobante_Comprobante_Devolucion { get; set; }
        public virtual ICollection<Comprobante_Recargo> Comprobante_Comprobante_Recargo { get; set; }
        public virtual ICollection<Comprobante_Remito> Comprobante_Comprobante_Remito { get; set; }
        public virtual ICollection<VentaArticuloPlanta> VentaArticuloPlanta { get; set; }
        public virtual ICollection<ArticuloPlanta> ArticuloPlanta { get; set; }
    }
}
