//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuestraPlanta
    {
        public long id { get; set; }
        public long idPlanta { get; set; }
        public long idMuestra { get; set; }
    
        public virtual Muestra Muestra { get; set; }
        public virtual Planta Planta { get; set; }
    }
}
