//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muestra
    {
        public Muestra()
        {
            this.DatosRutina = new HashSet<DatosRutina>();
            this.MuestraPlanta = new HashSet<MuestraPlanta>();
        }
    
        public long Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<DatosRutina> DatosRutina { get; set; }
        public virtual ICollection<MuestraPlanta> MuestraPlanta { get; set; }
    }
}
