//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuestraPlanta
    {
        public long id { get; set; }
        public long idPlanta { get; set; }
        public long idMuestra { get; set; }
    
        public virtual Muestra Muestra { get; set; }
        public virtual Planta Planta { get; set; }
    }
}
