//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPagoProveedor
    {
        public OrdenPagoProveedor()
        {
            this.ComprobanteProveedor = new HashSet<ComprobanteProveedor>();
            this.InstrumentoPago = new HashSet<InstrumentoPago>();
        }
    
        public long Id { get; set; }
        public string Numero { get; set; }
        public long IdProveedor { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public short Categoria { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<ComprobanteProveedor> ComprobanteProveedor { get; set; }
        public virtual ICollection<InstrumentoPago> InstrumentoPago { get; set; }
    }
}
