//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public long id { get; set; }
        public string nombre { get; set; }
        public string cuit { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string ingresosBrutos { get; set; }
        public Nullable<System.DateTime> inicioActividades { get; set; }
        public string email { get; set; }
        public string sitioWeb { get; set; }
        public Nullable<int> version { get; set; }
        public int idSituacionFrenteIva { get; set; }
    
        public virtual SituacionFrenteIva SituacionFrenteIva { get; set; }
    }
}
