//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presentacion
    {
        public Presentacion()
        {
            this.Entrada = new HashSet<Entrada>();
            this.VentaArticuloPlanta = new HashSet<VentaArticuloPlanta>();
            this.Salida = new HashSet<Salida>();
            this.PreciosAdicionales = new HashSet<PreciosAdicionales>();
        }
    
        public int id { get; set; }
        public int litrosEnvase { get; set; }
    
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual ICollection<VentaArticuloPlanta> VentaArticuloPlanta { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
        public virtual ICollection<PreciosAdicionales> PreciosAdicionales { get; set; }
    }
}
