//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.OrdenPagoProveedor = new HashSet<OrdenPagoProveedor>();
        }
    
        public long Id { get; set; }
        public string Cuit { get; set; }
        public string Denominacion { get; set; }
        public string Direccion { get; set; }
        public Nullable<long> IdLocalidad { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Localidad Localidad { get; set; }
        public virtual ICollection<OrdenPagoProveedor> OrdenPagoProveedor { get; set; }
    }
}
