//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida
    {
        public Salida()
        {
            this.Salida1 = new HashSet<Salida>();
        }
    
        public long id { get; set; }
        public Nullable<int> idPresentacion { get; set; }
        public string nroLote { get; set; }
        public decimal cantidad { get; set; }
        public Nullable<long> idCliente { get; set; }
        public string nombreVendedor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<long> idSalidaPadre { get; set; }
        public Nullable<long> idItemRemito { get; set; }
    
        public virtual Lote Lote { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual ICollection<Salida> Salida1 { get; set; }
        public virtual Salida Salida2 { get; set; }
        public virtual VentaArticuloPlanta VentaArticuloPlanta { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
