//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTarjeta
    {
        public TipoTarjeta()
        {
            this.Pago_Tarjeta = new HashSet<Pago_Tarjeta>();
        }
    
        public byte Id { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Pago_Tarjeta> Pago_Tarjeta { get; set; }
    }
}
