//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public Unidad()
        {
            this.Comprobante_Comprobante_Remito = new HashSet<Comprobante_Remito>();
            this.TipoArticulo = new HashSet<TipoArticulo>();
            this.TipoArticulo1 = new HashSet<TipoArticulo>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string abreviatura { get; set; }
    
        public virtual ICollection<Comprobante_Remito> Comprobante_Comprobante_Remito { get; set; }
        public virtual ICollection<TipoArticulo> TipoArticulo { get; set; }
        public virtual ICollection<TipoArticulo> TipoArticulo1 { get; set; }
    }
}
