//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public Unidad()
        {
            this.Comprobante_Comprobante_Remito = new HashSet<Comprobante_Remito>();
            this.TipoArticulo = new HashSet<TipoArticulo>();
            this.TipoArticulo1 = new HashSet<TipoArticulo>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string abreviatura { get; set; }
    
        public virtual ICollection<Comprobante_Remito> Comprobante_Comprobante_Remito { get; set; }
        public virtual ICollection<TipoArticulo> TipoArticulo { get; set; }
        public virtual ICollection<TipoArticulo> TipoArticulo1 { get; set; }
    }
}
