//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.FormularioUsuario = new HashSet<FormularioUsuario>();
            this.Log = new HashSet<Log>();
        }
    
        public int id { get; set; }
        public string nombreUsuario { get; set; }
        public string clave { get; set; }
        public bool inactivo { get; set; }
        public short idTipoUsuario { get; set; }
    
        public virtual ICollection<FormularioUsuario> FormularioUsuario { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
