//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.FormularioUsuario = new HashSet<FormularioUsuario>();
            this.Log = new HashSet<Log>();
        }
    
        public int id { get; set; }
        public string nombreUsuario { get; set; }
        public string clave { get; set; }
        public bool inactivo { get; set; }
        public short idTipoUsuario { get; set; }
    
        public virtual ICollection<FormularioUsuario> FormularioUsuario { get; set; }
        public virtual ICollection<Log> Log { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
