//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaArticuloPlanta
    {
        public VentaArticuloPlanta()
        {
            this.Salida = new HashSet<Salida>();
        }
    
        public long id { get; set; }
        public long idComprobante { get; set; }
        public long idArticulo { get; set; }
        public Nullable<long> idRemito { get; set; }
        public decimal cantidad { get; set; }
        public int idMoneda { get; set; }
        public decimal precio { get; set; }
        public decimal cotizacion { get; set; }
        public decimal iva { get; set; }
        public string lote { get; set; }
        public string descripAdicional { get; set; }
        public Nullable<int> idPresentacion { get; set; }
    
        public virtual Comprobante Comprobante { get; set; }
        public virtual Comprobante_Remito Comprobante_Comprobante_Remito { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual TipoArticulo TipoArticulo { get; set; }
        public virtual Presentacion Presentacion { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
    }
}
